### ISSUE TITLE
请问有“八嘎 hentai 无路赛”吗？

### ISSUE THREAD

**Issue by blackredscarf** [zthxxx/kugimiya-rainbow-fart#12]
RT

**Comment by zthxxx** [comment]
@blackredscarf 有的，语音文本对照在这里 

https://github.com/zthxxx/kugimiya-rainbow-fart/blob/master/resource.csv

对应第 11、37、03

![image](https://user-images.githubusercontent.com/15135943/85979068-71d23280-ba12-11ea-9838-a789b846b85c.png)
