### ISSUE TITLE
导入

### ISSUE THREAD

**Issue by qingyi-w** [zthxxx/kugimiya-rainbow-fart#14]
导入不进去
说缺少import Failed:voice Package should have a'manifest.h=json'file

**Comment by zthxxx** [comment]
报错截图来一个

**Comment by zthxxx** [comment]
@wangjiaqi-html 已复现 & 修复

see [release v1.0.2](https://github.com/zthxxx/kugimiya-rainbow-fart/releases/tag/v1.0.2) (https://github.com/zthxxx/kugimiya-rainbow-fart/releases/tag/v1.0.2)

ref: https://github.com/zthxxx/kugimiya-rainbow-fart/commit/705d81ba4803971cb6bf58b093fc459062108392#diff-b9e12334e9eafd8341a6107dd98510c9
