### ISSUE TITLE
使用npm ci后 使用npm run build 报错

### ISSUE THREAD

**Issue by findwinds** [zthxxx/kugimiya-rainbow-fart#15]
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
是在这下面^^^^^

SyntaxError: missing ) after argument list
    at Object.compileFunction (vm.js:379:18)
    at Generator.next (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kugimiya-rainbow-fart@1.0.2 gulp: `node -r esm node_modules/.bin/gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kugimiya-rainbow-fart@1.0.2 gulp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-08-13T03_05_19_337Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kugimiya-rainbow-fart@1.0.2 build: `npm run gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kugimiya-rainbow-fart@1.0.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-08-13T03_05_19_744Z-debug.log

想改一些自定义关键词

**Comment by zthxxx** [comment]
@qxf-findwind GitHub actions 中可以确认项目和 build 流程没有问题

https://github.com/zthxxx/kugimiya-rainbow-fart/runs/913457168?check_suite_focus=true#step:5:1

剩的可能就是 node 版本太低，或者不支持 windows 系统 (也不打算支持 win，请在 Linux / Unix / macOS) 下开发
