### ISSUE TITLE
English Version Please?

### ISSUE THREAD

**Issue by Stevemoretz** [zthxxx/kugimiya-rainbow-fart#16]
Hi I've been searching for one package that is English I'm using the intellij plugin rainbow fart,but couldn't find a thing.Would you please point me to the right direction?

Thanks in advance.

**Comment by zthxxx** [comment]
Note that this is a Japanese voice package.

if you just want give a try to this package, download the [last package](https://github.com/zthxxx/kugimiya-rainbow-fart/releases/download/v1.0.2/kugimiya-voice-1.0.2.zip) from GitHub Release (https://github.com/zthxxx/kugimiya-rainbow-fart/releases) ,

and then, unzip it in your folder before you write path in Intellij plugin rainbow fart.

I will Consider putting an English docs if you really think this package is worthy.

**Comment by Stevemoretz** [comment]
Thank you doesn't it include English voice then only Japanese right? Do you know any fork or branch that goes have English voice?

**Comment by zthxxx** [comment]
Japanese only.
