### ISSUE TITLE
里面有manifest.json文件，为什么失败呢？

### ISSUE THREAD

**Issue by JerryAndBun** [zthxxx/kugimiya-rainbow-fart#19]
![image](https://user-images.githubusercontent.com/75073060/100342989-b02a4880-2fd6-11eb-9f49-242f5291e171.png)

**Comment by zthxxx** [comment]
@JerryAndBun  是在 release 中下载的吗？

![image](https://user-images.githubusercontent.com/15135943/100350452-decf1000-3024-11eb-8e05-a9dd73ede1e5.png)

![image](https://user-images.githubusercontent.com/15135943/100350479-eee6ef80-3024-11eb-9b66-aa78921b8eea.png)
