### ISSUE TITLE
导入不进zip

### ISSUE THREAD

**Issue by lxzlxz** [zthxxx/kugimiya-rainbow-fart#2]
直接导入zip会显示 Import failed: voice package should have a "manifest.json" file

**Comment by zthxxx** [comment]
插件版本多少呢？

**Comment by zthxxx** [comment]
![image](https://user-images.githubusercontent.com/15135943/85219439-4ded6c00-b3d6-11ea-9590-017502704fd4.png)

![image](https://user-images.githubusercontent.com/15135943/85219444-59d92e00-b3d6-11ea-81b8-cd6fe02a1094.png)

**Comment by lxzlxz** [comment]
1.2.0 刚刚从vscode marketplace下载的

**Comment by lxzlxz** [comment]
我再确认一下 就是直接clone你这个repo 不改名字 然后直接去那个播放声音的页面点导入zip就可以直接导入了对吗 但我这里还是报错

**Comment by zthxxx** [comment]
clone 的方式是需要自己手动打包 zip 的，否则不能导入，

我在 release 中放了打包好的 zip 文件可以直接下载使用，

https://github.com/zthxxx/kugimiya-rainbow-fart/releases

![image](https://user-images.githubusercontent.com/15135943/85219569-96f1f000-b3d7-11ea-90a6-19145ba9e389.png)

**Comment by lxzlxz** [comment]
可以了 辛苦
