### ISSUE TITLE
是否可以在clone处下载zip然后手动导入？

### ISSUE THREAD

**Issue by Kennnnnnji** [zthxxx/kugimiya-rainbow-fart#3]
![image](https://user-images.githubusercontent.com/34367558/85221371-fa831a00-b3e5-11ea-9375-9f55cca7d60e.png)
解压到语音包目录，并重命名文件夹，删除`-master`（重要，不删除`-master`会导致fart无法正常工作）
![image](https://user-images.githubusercontent.com/34367558/85221380-07a00900-b3e6-11ea-81a2-d8f519d3268d.png)
![image](https://user-images.githubusercontent.com/34367558/85221383-0a9af980-b3e6-11ea-9cea-6201f21ac018.png)

**Comment by zthxxx** [comment]
不，不，这里下载的 zip 不能用，因为内部 json 文件会互相合并导致信息不对

**Comment by zthxxx** [comment]
build zip 有用命令过滤掉了不需要的文件，比如 `package.json`

**Comment by zthxxx** [comment]
> 不，不，这里下载的 zip 不能用，因为内部 json 文件会互相合并导致信息不对

@Kennnnnnji 
问题类似这个 https://github.com/zthxxx/kugimiya-rainbow-fart/pull/1#issuecomment-647096518

`load()` 时会合并所有 json 文件，导致 `manifest` 被污染

**Comment by Kennnnnnji** [comment]
我在这样尝试后能够正常运行 QAQ

**Comment by zthxxx** [comment]
> 我在这样尝试后能够正常运行 QAQ

但是 name, description 和文件目录名都不对了

**Comment by zthxxx** [comment]
@Kennnnnnji  

而且 release 表示是经过测试和稳定的版本，

但是 master 上的代码可能有些新的问题或者不太稳定，

总之目前不建议这么用，但是已经了解你说的这个方案了，后续我会再优化下 json 合并问题

**Comment by zjffun** [comment]
我试了下貌似是因为 git clone 下载下来的 `kugimiya-rainbow-fart-master.zip` 多了一层 `kugimiya-rainbow-fart-master` 文件夹

**Comment by zthxxx** [comment]
> 我试了下貌似是因为 git clone 下载下来的 `kugimiya-rainbow-fart-master.zip` 多了一层 `kugimiya-rainbow-fart-master` 文件夹

对呀，这样导入的时候也会报错的吧， 反而你之前说能成功运行才是不正常呢

**Comment by zjffun** [comment]
额 我看错了。。我当这个 issue 说 “不可以在clone处下载zip然后手动导入” ，然后我试了下多了一层 kugimiya-rainbow-fart-master 文件夹所以不能导入
