### ISSUE TITLE
文本对照有么老哥

### ISSUE THREAD

**Issue by baifengbai** [zthxxx/kugimiya-rainbow-fart#4]

**Comment by zthxxx** [comment]
还没有来得及整理，在 TODO 里面

**Comment by baifengbai** [comment]
人肉翻译了，谢谢

**Comment by zthxxx** [comment]
> 人肉翻译了，谢谢

@baifengbai PR 来一嘛个～

**Comment by zthxxx** [comment]
文本台词对照加了

https://github.com/zthxxx/kugimiya-rainbow-fart/blob/v1.0.0/resource.csv
