### ISSUE TITLE
文件加名称要和manifest的name相同，要不找不到文件

### ISSUE THREAD

**Issue by DawnSouther** [zthxxx/kugimiya-rainbow-fart#5]
rt,release可以重新打个包

**Comment by zthxxx** [comment]
是哪个文件找不到呢？ 我每个key 对应的语音都听过一遍，没看到找不到都的

**Comment by DawnSouther** [comment]
![image](https://user-images.githubusercontent.com/22205542/85253640-37f0b180-b491-11ea-8667-4ed81fe4fcd7.png)
![image](https://user-images.githubusercontent.com/22205542/85253666-46d76400-b491-11ea-9869-ad262aa002fa.png)
这两个地方，因为你的release是打包0.0.1版本嘛，需要手动修改下名字。

**Comment by zthxxx** [comment]
不需要呀，在导入的时候自动会被 vscode-rainbow-fart 改名的，

甚至不需要手动解压， vscode-rainbow-fart 自己做了解压的操作

**Comment by zthxxx** [comment]
![import](https://github.com/zthxxx/kugimiya-rainbow-fart/raw/master/preview/import.png)

**Comment by DawnSouther** [comment]
我没注意到（手动狗头）。
