### ISSUE TITLE
怎么导入进去  求老铁  讲解一手  球球了

### ISSUE THREAD

**Issue by songyueying** [zthxxx/kugimiya-rainbow-fart#7]

**Comment by zthxxx** [comment]
README 里面有手把手教的呀

https://github.com/zthxxx/kugimiya-rainbow-fart#install


![image](https://user-images.githubusercontent.com/15135943/85350264-48f1ff00-b533-11ea-9286-f302ac04bf8b.png)

**Comment by songyueying** [comment]
找不到这个插件的setting配置页面  我导入进入 显示失败呀...

**Comment by songyueying** [comment]
![image](https://user-images.githubusercontent.com/67146567/85351130-8fe0f400-b535-11ea-8b5f-be69f48ab993.png)
他显示导入不进去呀

**Comment by zthxxx** [comment]
vscode 插件版本多少？

zip 有没有下错地方，你的 zip 在哪儿下载的

![image](https://user-images.githubusercontent.com/15135943/85351228-cd458180-b535-11ea-8329-9bf1bdf719eb.png)

**Comment by songyueying** [comment]
好使了  铁铁  下错文件了 o(╥﹏╥)o

**Comment by zthxxx** [comment]
> 好使了 铁铁 下错文件了 o(╥﹏╥)o

所以你在哪儿下的？
